export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_SETQUENCE_LIST = 'SET_SETQUENCE_LIST'

export const SET_PLAYING_LIST = 'SET_PLAYING_LIST'

export const SET_MODE = 'SET_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_LISTITEM = 'SET_LISTITEM'

export const SET_CURRENTSONG = 'SET_CURRENTSONG'